import type { Metadata } from "next";
import WagmiWrapper from "../providers/WagmiProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-y-scroll bg-gray-1100 bg-grid pb-36`}
      >
        <WagmiWrapper>{children}</WagmiWrapper>
      </body>
    </html>
  );
}
