import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import WagmiWrapper from "../providers/WagmiProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-y-scroll bg-gray-1100 bg-grid pb-36`}
      >
        <WagmiWrapper>{children}</WagmiWrapper>
      </body>
    </html>
  );
}
